FROM php:8.4
WORKDIR /api
#パッケージのインストール
COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_HOME="/opt/composer"
ENV PATH="$PATH:/opt/composer/vendor/bin"
RUN apt-get update \
    && apt-get install -y zip libpq-dev \
    && docker-php-ext-install pdo_pgsql pgsql

    #以下の内容を追記
COPY . .
WORKDIR /api/laravel-app
RUN composer install
CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]
EXPOSE 8000

